baseURL = "https://metadonors.github.io/odoo.workshop/"
languageCode = "it-it"
title = "Odoo Workshop"
publishDir = "docs"
theme = "learn"

[params]
editURL = "https://github.com/metadonors/odoo.workshop/tree/master/content/"
# Author of the site, will be used in meta information
author = "Metadonors"
description = "Odoo Workshop"
themeVariant = "metadonors"
ordersectionsby = "weight"


[outputs]
home = [ "HTML", "RSS", "JSON"]
